services:
  # Eureka Discovery Server
  discovery:
    container_name: Discovery
    build: ./Discovery
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=Discovery
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - my-network

  # Doctor Microservice
  # DirectionFinanciere:
  #   container_name: DirectionFinanciere
  #   build: ./DirectionFinanciere
  #   image: web-directionfinanciere # <-- Changed to lowercase
  #   ports:
  #     - "9095:9095"
  #   environment:
  #     - SPRING_APPLICATION_NAME=DirectionFinanciere
  #     - SERVER_PORT=9095
  #     - eureka.client.serviceUrl.defaultZone=http://Discovery:8761/eureka/
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/microservice?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=
  #   depends_on:
  #     - Discovery
  #     - db-mysql

  # API Gateway
  # api-gateway:
  #   container_name: Gateway
  #   build: ./api-gateway
  #   ports:
  #     - "8090:8090"
  #   environment:
  #     - SPRING_APPLICATION_NAME=Gateway
  #     - SERVER_PORT=8090
  #     - eureka.client.serviceUrl.defaultZone=http://Discovery:8761/eureka/
  #   depends_on:
  #     - Discovery
  #     - DirectionFinanciere

#ketlock
  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   environment:
  #     - KEYCLOAK_ADMIN=admin  # New admin user variable
  #     - KEYCLOAK_ADMIN_PASSWORD=admin  # New admin password variable
  #     - KC_DB=postgres  # Updated DB vendor option
  #     - KC_DB_URL_HOST=db  # Updated database host
  #     - KC_DB_USERNAME=keycloak
  #     - KC_DB_PASSWORD=password
  #     - KC_DB_DATABASE=keycloak
  #   command: [ "start-dev" ]  # Using start-dev mode for development
  #   ports:
  #       - "8080:8080"
  #   depends_on:
  #       - db

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  # Base de données MySQL pour Doctor Microservice
  db-mysql:
    container_name: db-mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - my-network

  app:
    build:
      context: ./micro-service-student
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/mardi?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_SHOW_SQL: "false"
      FILE_UPLOAD_DIR: ./uploads
    depends_on:
      - db-mysql
      - micro-service-contact
    networks:
      - my-network

  micro-service-contact:
    build:
      context: ./micro-service-contact
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb://db-mongo:27017/contactdb
      - JWT_SECRET=mysecretkey
      - NODE_ENV=development
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
    depends_on:
      - db-mongo
      - discovery
    networks:
      - my-network


  db-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=contactdb
    networks:
      - my-network

volumes:
  db-data:

networks:
  my-network:
    driver: bridge