version: '3'
services:
  micro-service-contact:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb://db:27017/contactdb
      - JWT_SECRET=mysecretkey
      - NODE_ENV=development
    depends_on:
      - db-mongo

  db-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
